
name = "main"
#name = "aoc-fortran"
version = "0.1.0"
license = "BSD 3-Clause"
author = "Jeff Irwin"
maintainer = "jirwin505@gmail.com"
copyright = "Copyright 2025, Jeff Irwin"

[library]
include-dir = [ "../../src/include" ]

#[library]
#source-dir = "."
[[executable]]
name = "main"
source-dir = "."

#[dependencies]
##my-utils = { path = "utils" }
#aoc-fortran = { path = "../../src" }

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
#external-modules = ["netcdf", "h5lt"]
#external-modules = ["../../src/include/"]
link = ["aoc-fortran"]
external-modules = ["/home/jirwi/git/aoc-fortran/src/include/"]

[install]
library = true
test = false

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

