
name = "aoc-fortran"
version = "0.1.0"
license = "BSD 3-Clause"
author = "Jeff Irwin"
maintainer = "jirwin505@gmail.com"
copyright = "Copyright 2025, Jeff Irwin"

[library]
source-dir = "."

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true
test = false

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

